apiVersion: v1
kind: Service
metadata:
  name: brandsconsumer
  labels:
    app: brandsconsumer
spec:
  selector:
    app: brandsconsumer
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8060
    nodePort: 31200
  - name: https
    port: 443
    targetPort: 8443
    nodePort: 31201
    

